@ProbabilityCalculatorAPI_HostAddress = http://localhost:5184

### Test CombinedWith Operation
POST {{ProbabilityCalculatorAPI_HostAddress}}/api/calculation/calculate
Content-Type: application/json
Accept: application/json

{
  "probabilityA": 0.5,
  "probabilityB": 0.5,
  "operationType": "CombinedWith"
}

### Test Either Operation
POST {{ProbabilityCalculatorAPI_HostAddress}}/api/calculation/calculate
Content-Type: application/json
Accept: application/json

{
  "probabilityA": 0.5,
  "probabilityB": 0.5,
  "operationType": "Either"
}
